// AUTO-GENERATED by scripts/generate-feast-index.js - do not edit by hand.
// It is regenerated automatically before every `npm run dev` / `npm run build`.
// To add a day: just add its JSON file under src/data/feasts/ and rerun
// either command (or push - Vercel runs `npm run build` too).

import type { FeastDay, FeastKey } from '@/types/feast';
import feast_1_1 from './1-1.json';
import feast_1_9 from './1-9.json';
import feast_1_10 from './1-10.json';

const registry: Record<FeastKey, FeastDay> = {
  '1-1': feast_1_1 as FeastDay,
  '1-9': feast_1_9 as FeastDay,
  '1-10': feast_1_10 as FeastDay,
};

export function getFeastByKey(key: FeastKey): FeastDay | undefined {
  return registry[key];
}

export function getAllFeastKeys(): FeastKey[] {
  return Object.keys(registry) as FeastKey[];
}

export function getAllFeasts(): FeastDay[] {
  return Object.values(registry);
}
